import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  OrganizationSwitcher,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* ─────── ヘッダー ─────── */}
          <header className="flex justify-end items-center gap-4 h-16 px-4 border-b">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>

            <SignedIn>
              <OrganizationSwitcher
                hidePersonal
                appearance={{
                  elements: {
                    organizationSwitcherTrigger: 'rounded-full h-10',
                  },
                }}
              />
              <UserButton afterSignOutUrl="/" />
            </SignedIn>
          </header>

          {/* ─────── メインコンテンツ ─────── */}
          <main className="flex min-h-screen">
            {/* サイドバー */}
            <aside className="w-32 bg-gray-100 border-r p-4">
              <nav className="flex flex-col gap-4">
                <Link href="/dashboard/image-generation" className="hover:underline">画像生成</Link>
                <Link href="/dashboard/video-generation" className="hover:underline">動画生成</Link>
                <Link href="/history" className="hover:underline">生成履歴</Link>
              </nav>
            </aside>

            {/* ページの中身 */}
            <section className="flex-1 p-6 overflow-auto">
              {children}
            </section>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
